document.writeln("<!-- 页脚 -->");
document.writeln("    <div class=\"width100 float_l backg_shhu height240\">");
document.writeln("    	<div class=\"width_1320 margin_auto\">");
document.writeln("        ");
document.writeln("        	<div class=\"width_360 float_l margin_t70\">");
document.writeln("            	<div class=\"width100 float_l margin_b8\">");
document.writeln("                	<img data-original=\"img/uiz19.png\" src=\"img/grey.gif\" height=\"39\" border=\"0\" />");
document.writeln("                </div>");
document.writeln("                <div class=\"width100 float_l color_white fon_siz13 line_hei13\">");
document.writeln("                	<span>中国家电研究院旗下网站</span>");
document.writeln("                    <span>|</span>");
document.writeln("                    <span>权威智能家电家居新媒体平台</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <div class=\"width_350 float_l margin_t50\">");
document.writeln("                <div class=\"width_130 height130 float_l margin_r20 margin_l20\">");
document.writeln("                	<div class=\"width100 float_l img_backg1 margin_b10\">");
document.writeln("                    	<img data-original=\"img/uiz20.png\" src=\"img/grey.gif\" height=\"130\" border=\"0\" />");
document.writeln("                    </div>");
document.writeln("                    <div class=\"width100 float_l text_c color_white\">");
document.writeln("                        <span>扫码关注微信</span>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <div class=\"width_130 height130 float_l\">");
document.writeln("                	<div class=\"width100 float_l img_backg1 margin_b10\">");
document.writeln("                    	<img data-original=\"img/uiz21.png\" src=\"img/grey.gif\" height=\"130\" border=\"0\" />");
document.writeln("                    </div>");
document.writeln("                    <div class=\"width100 float_l text_c color_white\">");
document.writeln("                        <span>扫码访问手机版</span>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <div class=\"width_610 float_l margin_t65\">");
document.writeln("            	<div class=\"width100 float_l margin_b15\">");
document.writeln("                	<ul class=\"width100 float_l ulli_float color_white fon_siz13\">");
document.writeln("                    	<li><a target=\"_blank\" href=\"http://www.baidu.com\">智享首页</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">新品发现</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">种加点排行榜</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">评测</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">视频</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">新品试用</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">会员福利</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">网站地图</a></li>");
document.writeln("                        <li class=\"margin_lr8 color_qianh\">|</li>");
document.writeln("                        <li><a target=\"_blank\" href=\"http://www.baidu.com\">手机版</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\"width100 float_l fon_siz13 color_white margin_b15\">");
document.writeln("                	<span>违法和不良信息举报 admin(a)wisenjoy.com 商务合作 sales(a)wisenjoy.com</span>");
document.writeln("                </div>");
document.writeln("                <div class=\"width100 float_l fon_siz13 color_white margin_b15\">");
document.writeln("                	<span>京ICP备1402626号 京ICP证1532222号 京网文20150493-123号 京公网安备11010802027191号</span>");
document.writeln("                </div>");
document.writeln("                <div class=\"width100 float_l fon_siz13 color_white\">");
document.writeln("                	<span>Powered by wisenjoy 20101-2013 Comsenz Inc.中国家电研究院智慧家庭研究中心</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("	</div>  ");
document.writeln("</div>");