document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"utf-8\">");
document.writeln("<title>HTML素材网-演示模板-首页</title>");
document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/css/bootstrap.css\">");
document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/pc_currency.css\">");
document.writeln("<script type=\"text/javascript\" src=\"js/thrid_libs/jquery.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"js/thrid_libs/jquery.SuperSlide.2.1.1.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"js/thrid_libs/jquery.lazyload.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"js/pc_other/tabSwitch.js\"></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=\"width100 float_l backg_beihui posi_relative\">");
document.writeln("	<!-- 顶部logo  S-->");
document.writeln("	<div class=\"width100 float_l height100 backg_white posi_relative\">");
document.writeln("    	<div class=\"width_1320 margin_auto\">");
document.writeln("        ");
document.writeln("        	<!-- 左侧logo -->");
document.writeln("        	<div class=\" width_400 float_l margin_t20\">");
document.writeln("            	<div class=\"width100 float_l margin_b8\">");
document.writeln("                    <img data-original=\"img/uiz1.png\" src=\"img/grey.gif\" height=\"39\" border=\"0\" />");
document.writeln("                </div>");
document.writeln("                <div class=\"width100 float_l fon_siz13 line_hei13\">");
document.writeln("                	<span>中国家电研究院旗下网站</span>");
document.writeln("                    <span>|</span>");
document.writeln("                    <span>权威智能家电家居新媒体平台</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <!-- 中间搜索 -->");
document.writeln("        	<div class=\"width_430 float_l margin_t30\">");
document.writeln("            	<div class=\"width_300 input_sty margin_auto\">");
document.writeln("                	<div class=\"float_l posi_relative posi_rel posi_abs cursor_po\">");
document.writeln("                	<input type=\"text\" name=\"\"  id=\"\" value=\"\" placeholder=\"请输入关键词\"/>");
document.writeln("                    <img data-original=\"img/uiz2.png\" src=\"img/grey.gif\" height=\"18\" border=\"0\" />");
document.writeln("                    </div>         ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("            <!-- 右侧信息 -->");
document.writeln("        	<div class=\" width_450 float_r line_hei100\">");
document.writeln("            	<div class=\"float_r\">");
document.writeln("                    <div class=\"float_l margin_r28 backg_img2\">");
document.writeln("                        <span>加入</span>");
document.writeln("                        <img class=\"margin_t-2\" data-original=\"img/uiz11.png\" src=\"img/grey.gif\" height=\"12\" border=\"0\" />");
document.writeln("                        <span>，专属会员权益随时享</span>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"float_l\">");
document.writeln("                    	<div class=\"float_l margin_t-2\"><img data-original=\"img/uiz3.png\" src=\"img/grey.gif\" height=\"13\" border=\"0\" /></div>");
document.writeln("                        <div class=\"float_l margin_l5\"><a target=\"_blank\" href=\"land.html\">登录</a></div>");
document.writeln("                        <div class=\"float_l margin_lr5\"><span>|</span></div>");
document.writeln("                        <div class=\"float_l\"><a target=\"_blank\" href=\"register.html\">注册</a></div>");
document.writeln("                    </div>");
document.writeln("            	</div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- 顶部logo  E-->");
document.writeln("    ");
document.writeln("    <!-- 导航栏  S-->");
document.writeln("    <div class=\"width100 float_l backg_red height44 posi_relative\">");
document.writeln("    	<div class=\"width_1320 margin_auto\">");
document.writeln("        	<div class=\"width_184 float_l line_hei44 whole\">");
document.writeln("            	<div class=\"width100 float_l backg_hui padding_lr10 sur_def\">");
document.writeln("                    <div class=\"float_l\">");
document.writeln("                        <img data-original=\"img/uiz7.png\" src=\"img/grey.gif\" height=\"23\" border=\"0\" />");
document.writeln("                    </div>");
document.writeln("                    <div class=\"float_l color_white fon_siz16 margin_l30\">");
document.writeln("                        <span>全部产品</span>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"float_r\">");
document.writeln("                        <img data-original=\"img/uiz8.png\" src=\"img/grey.gif\" height=\"7\" border=\"0\" />");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\"width_786 float_l\">");
document.writeln("            	<div class=\"width100 float_l color_white fon_siz14 li_float line_hei44\">");
document.writeln("                	<ul class=\"width100 float_l\">");
document.writeln("                    	<li id=\"naon_1\" class=\"margin_l20\"><a target=\"_blank\" href=\"index.html\">首页</a></li>");
document.writeln("                        <li id=\"naon_2\"><a target=\"_blank\" href=\"discoveryList.html\">发现</a></li>");
document.writeln("                        <li id=\"naon_3\"><a target=\"_blank\" href=\"http://www.baidu.com\">排行榜</a></li>");
document.writeln("                        <li id=\"naon_4\"><a target=\"_blank\" href=\"http://www.baidu.com\">测评</a></li>");
document.writeln("                        <li id=\"naon_5\"><a target=\"_blank\" href=\"http://www.baidu.com\">视频</a></li>");
document.writeln("                        <li id=\"naon_6\"><a target=\"_blank\" href=\"http://www.baidu.com\">新品试用</a></li>");
document.writeln("                        <li id=\"naon_7\"><a target=\"_blank\" href=\"http://www.baidu.com\">会员福利</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\"width350 float_r\">");
document.writeln("            	<div class=\"float_r line_hei44\">");
document.writeln("                	<div class=\"float_l margin_r17\">");
document.writeln("                    	<div class=\"float_l margin_r5\">");
document.writeln("                        	<img data-original=\"img/uiz4.png\" src=\"img/grey.gif\" height=\"24\" border=\"0\" />");
document.writeln("                        </div>");
document.writeln("                        <div class=\"float_l color_white fon_siz14\">");
document.writeln("                        	<a target=\"_blank\" href=\"http://www.baidu.com\">微信抽奖</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"float_l margin_r17\">");
document.writeln("                    	<div class=\"float_l margin_r5\">");
document.writeln("                        	<img data-original=\"img/uiz5.png\" src=\"img/grey.gif\" height=\"24\" border=\"0\" />");
document.writeln("                        </div>");
document.writeln("                        <div class=\"float_l color_white fon_siz14\">");
document.writeln("                        	<a target=\"_blank\" href=\"http://www.baidu.com\">积分兑换</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"float_l\">");
document.writeln("                    	<div class=\"float_l margin_r5\">");
document.writeln("                        	<img data-original=\"img/uiz6.png\" src=\"img/grey.gif\" height=\"24\" border=\"0\" />");
document.writeln("                        </div>");
document.writeln("                        <div class=\"float_l color_white fon_siz14\">");
document.writeln("                        	<a target=\"_blank\" href=\"http://www.baidu.com\">1分钱秒杀</a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"width100 float_l backg_white posi_relative z_inx_777 full_details dis_none\">");
document.writeln("            <div class=\"width_1320 margin_auto\">");
document.writeln("            	<div class=\"width100 float_l padding_tb30 div_dt div_dd\">");
document.writeln("                    <div class=\"width_219 float_l padding_lr20 border_l_color height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt class=\"decoration\">全部产品展示</dt>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                ");
document.writeln("                    <div class=\"width_219 float_l padding_lr20 border_l_color line_hei24 height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt>大家电</dt> ");
document.writeln("                            <dd>电视</dd>");
document.writeln("                            <dd>空调</dd>");
document.writeln("                            <dd>洗衣机</dd>");
document.writeln("                            <dd>冰箱</dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                    ");
document.writeln("                    <div class=\"width_218 float_l padding_lr20 border_l_color height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt>厨卫大电</dt> ");
document.writeln("                            <dd>油烟机</dd>");
document.writeln("                            <dd>燃气灶</dd>");
document.writeln("                            <dd>洗碗机</dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"width_218 float_l padding_lr20 border_l_color height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt>厨房小电</dt> ");
document.writeln("                            <dd>电饭煲</dd>");
document.writeln("                            <dd>微波炉</dd>");
document.writeln("                            <dd>电烤箱</dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"width_218 float_l padding_lr20 border_l_color height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt>生活电器</dt> ");
document.writeln("                            <dd>饮水机</dd>");
document.writeln("                            <dd>扫地机器人</dd>");
document.writeln("                            <dd>吸尘器</dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                    ");
document.writeln("                    <div class=\"width_222 float_l padding_lr20 border_l_color height130\">");
document.writeln("                        <dl>");
document.writeln("                            <dt>个体健康</dt> ");
document.writeln("                            <dd>按摩椅</dd>");
document.writeln("                            <dd>足浴盆</dd>");
document.writeln("                            <dd>血糖仪</dd>");
document.writeln("                        </dl>");
document.writeln("                    </div>");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("    </div>");
document.writeln("    <!-- 导航栏  E-->");